### ISSUE TITLE
Highlight in Ctrl + Shift + F

### ISSUE THREAD

**Issue by BButner** [frykher/jetbrains-kanagawa-theme#3]
If you see the below image, using Ctrl + Shift + F to "Find in Files", the highlight text color and background makes it almost unreadable:

![image](https://user-images.githubusercontent.com/39167186/216165520-a470f810-30ef-4e35-8337-5d5bcda80561.png)

**Comment by Manuzor** [comment]
This is the main blocker for me. I've been skimming through the catppuccin theme, which doesn't have this problem, and found that they're defining `selectionInactiveForeground` (see screenshot) while Kanagawa Theme doesn't. Maybe that is the problem?

![image](https://github.com/frykher/jetbrains-kanagawa-theme/assets/5539930/bf2a77f2-1c0d-4080-9600-c20670b2bf4a "catppuccin theme defining selectionInactiveForeground")

Unfortunately I don't know how to test locally, otherwise I'd create a PR.

**Comment by frykher** [comment]
Is this still a problem for anyone? I don't think that setting has any effect anymore in version 2024.1. I'm using the macOS version.
<img width="666" alt="image" src="https://github.com/frykher/jetbrains-kanagawa-theme/assets/62032183/531e25b5-d7ea-420a-acf4-3fc3620bb06b">

**Comment by Jonassen** [comment]
I'm still having this problem in IDEA Ultimate 2024.2 on MacOS with plugin version 1.1.6. 
I'm not aware of any colors I've overridden.

**Comment by frykher** [comment]
Fixed by 56ff4f9
